display_name: spotifyre
icon: assets/spotifyre-logo.png

keywords:
  - Music
  - Spotify
  - Media
  - Streaming
  - YouTube

generic_name: Music Streaming Application
categories:
  - Music

supported_mime_type:
  - x-scheme-handler/spotify
