app_id: 80B901C8-D6FE-494E-8AF7-A2BD440E8644
publisher: KRTirtho, OSS
publisher_url: https://github.com/KRTirtho/spotifyre
display_name: spotifyre
create_desktop_icon: true
install_dir_name: spotifyre
script_template: inno_setup.iss
locales:
  - en
